---
title: "DataFramed Podcast Reviews"
format: html
editor: visual
---

## Can we Create an AI Doctor? with Aldo Faisal, Professor in AI & Neuroscience at Imperial College

	This podcast was presented by Dr. Aldo Faisal and discussed the role of AI in healthcare. Key takeaways from this podcast were:

-   Utilize federated machine learning to train AI models on sensitive healthcare data while preserving patient privacy, enabling the development of robust AI systems without compromising data security.

-   Investigate the potential of ambient intelligence in healthcare, which automates operational tasks like transcribing doctor-patient conversations and updating patient records, to reduce administrative burdens and enhance clinical decision-making.

-   Consider the development of large health models, akin to large language models, that can process multimodal data from electronic health records, medical literature, and research data to provide comprehensive insights into patient care and treatment outcomes.

\

Reading the title of the podcast, what immediately came to mind was an AI robot doctor that you would see on TV. This is what Dr. Faisal mentioned in the beginning of the podcast, that this is not to be mistaken with just that. Using AI in the medical field can help doctors and nurses treat patients faster and more accurately. An example of how AI has helped within the medical space has been regarding diagnostics. According to Dr. Faisal, licenses for these are already in the process of being licensed and used in the workspace. AI can be used to help tumor/shadow detection on scans, transcribe a conversation between a doctor and patient, identify symptoms, make suggestions on medication, and prefill information to make the doctor's clerical load lighter. 

\

Nightingale AI is the name of Dr. Faisal’s project. Based in the UK, this is a large health model trained in electronic health records, imaging, labs, genetics, pathology, telemetry, and literature. The purpose is to have support provided for healthcare providers. Their main concern was how to obtain large amounts of medical data, which includes cooperating with healthcare providers and patients, and what to do with the data. It was mentioned that patients were concerned regarding their privacy and for their data to not be abused. However, Dr. Faisal stated that the main idea is to create an AI that learns about medicine in a different way that other large language models are applied to. They want to build models that are trained on multimodal data, so that the model is able to ingest, understand, and reason information the same way a medical doctor would reason science. 

\

They are working actively with the NHS, (National Health Service), on training and building the system that honors the privacy of the data provided. It is called Federate Machine Learning, and there is still research and development that needs to be done. 

\

Example given of how Nightingale AI will help doctors in the future: 

-   Ex. The patient has a chest infection and the doctor will prescribe a certain type of penicillin. The system then can predict how the patient's xray will look depending on what type of medicine that is prescribed to the patient. 

-   Ex. The patient has liver issues and the doctor prescribes a drug to cure another issue in the kidney. How will this medication affect your liver and what are all of the possible side effects and how do all of these drugs interact with each other? What are all the positive and negative side effects? 

-   Polypharmacy problem - this is what pharma researchers want to know when testing a medicine and which populations they can test on without issues. 

-   Ex. Can be used to understand how a patient evolves - the system has a “digital twin” which includes a description of your body’s physiology. This would be useful to see how an asthmatic patient would do in an environment that is hot, polluted, and can potentially save many lives

\

Nightingale AI is intended for use by AI, digital health, and clinical researchers so it can be focused on user experience and interface. Once the system evolves with a proper chat conversation prompt, it can be expanded for use within the general population

\

Dr Faisal mentioned something that stuck with me. Concerning patients and their data privacy, he mentioned that sick patients almost always give their data away. They want to give their data to get better and to help others who are sick as well. The aim of the healthy is to not give their data away. There are different laws that protect people and their data, as well as how it can be used by insurers or employers. Data leakage is a possible risk however they are considering that as well. 

\

Overall, this particular podcast gave some amazing insights into the use of AI within the healthcare sector. I am not familiar with the healthcare world, so this was very insightful and allowed me to understand more of how AI can be used around the world. 
